import type { ReviewPolicyRule } from '../domain/types.js';

export const REVIEW_POLICY_VERSION = 1;

export const DEFAULT_REVIEW_POLICIES: ReviewPolicyRule[] = [
  {
    id: 'prod-high-risk',
    review_type: 'PRODUCTION',
    required: true,
    blocking: true,
    blocks_execution: true,
    priority: 'HIGH',
    reason: 'High/critical risk change that affects production',
    when: { risk_levels: ['HIGH', 'CRITICAL'], affects_production: true },
    version: REVIEW_POLICY_VERSION,
  },
  {
    id: 'arch-high-impact',
    review_type: 'ARCHITECTURE',
    required: true,
    blocking: false,
    blocks_execution: false,
    priority: 'HIGH',
    reason: 'High architecture impact requires architecture review',
    when: {
      architecture_impact: ['high', 'critical'],
      impact_recommendations: ['ARCHITECTURE_REVIEW_REQUIRED'],
    },
    version: REVIEW_POLICY_VERSION,
  },
  {
    id: 'proposed-adr',
    review_type: 'ARCHITECTURE',
    required: true,
    blocking: true,
    blocks_execution: false,
    priority: 'HIGH',
    reason: 'Proposed ADR requires human accept/reject',
    when: { has_proposed_adrs: true },
    version: REVIEW_POLICY_VERSION,
  },
  {
    id: 'security-sensitive',
    review_type: 'SECURITY',
    required: true,
    blocking: true,
    blocks_execution: false,
    priority: 'HIGH',
    reason: 'Security-sensitive change',
    when: { security_sensitive: true },
    version: REVIEW_POLICY_VERSION,
  },
  {
    id: 'schema-change',
    review_type: 'DATA',
    required: true,
    blocking: true,
    blocks_execution: false,
    priority: 'HIGH',
    reason: 'Database/schema change',
    when: { schema_change: true },
    version: REVIEW_POLICY_VERSION,
  },
  {
    id: 'deployment-change',
    review_type: 'PRODUCTION',
    required: true,
    blocking: true,
    blocks_execution: false,
    priority: 'HIGH',
    reason: 'Deployment-related change',
    when: { deployment_change: true },
    version: REVIEW_POLICY_VERSION,
  },
  {
    id: 'large-refactor',
    review_type: 'CODE',
    required: true,
    blocking: false,
    blocks_execution: false,
    priority: 'MEDIUM',
    reason: 'Large refactor',
    when: { large_refactor: true },
    version: REVIEW_POLICY_VERSION,
  },
  {
    id: 'verification-fail',
    review_type: 'QUALITY',
    required: true,
    blocking: false,
    blocks_execution: false,
    priority: 'MEDIUM',
    reason: 'Verification failures present',
    when: { verification_failures: true },
    version: REVIEW_POLICY_VERSION,
  },
  {
    id: 'conflicting-evidence',
    review_type: 'QUALITY',
    required: true,
    blocking: true,
    blocks_execution: false,
    priority: 'HIGH',
    reason: 'Conflicting evidence in the architecture graph',
    when: { conflicting_evidence: true },
    version: REVIEW_POLICY_VERSION,
  },
  {
    id: 'low-confidence',
    review_type: 'QUALITY',
    required: true,
    blocking: false,
    blocks_execution: false,
    priority: 'MEDIUM',
    reason: 'Low outcome confidence',
    when: { max_outcome_confidence: 0.5 },
    version: REVIEW_POLICY_VERSION,
  },
];
